development:
  adapter: mysql2
  database: spectrum_dev
  username: spectrum_dev
  password: EJtdCvhctAupxDrJ
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: spectrum
  username: spectrum
  password: LxPNAHXycbbYFThu 
  host: localhost
